### ISSUE TITLE
Discrepancy in documentation and code

### ISSUE THREAD

**Issue by siddharthlal25** [JuliaAstro/DustExtinction.jl#11]
In the documentation of `cal00` the default value for Rv is mentioned as `4.05` https://github.com/JuliaAstro/DustExtinction.jl/blob/a39125be77a98b8c397724199e3b389cb82e331f/src/color_laws.jl#L100

Whereas in the function default value of Rv is taken as `3.1`
https://github.com/JuliaAstro/DustExtinction.jl/blob/a39125be77a98b8c397724199e3b389cb82e331f/src/color_laws.jl#L117

**Comment by giordano** [comment]
Good spot!  The docstring was changed in https://github.com/JuliaAstro/DustExtinction.jl/pull/7, before it was reporting 3.1, consistent with the default value defined in the function.  CC: @mileslucas

**Comment by mileslucas** [comment]
Thanks for the catch! I'll make the change, along with pushing the new version of documenter in an upcoming PR
