### ISSUE TITLE
Redundant utility function

### ISSUE THREAD

**Issue by siddharthlal25** [JuliaAstro/DustExtinction.jl#23]
The general format of a model is of the form: `model(λ::Real, Rv = 3.1)`
and if `λ` is `Quantity`, then we have a modified definition to the function call being:
`model(λ::Quantity, Rv::Real = 3.1) = model(ustrip(u"angstrom", λ), Rv) * u"mag"`.

Therefore function `aa_to_invum` in each of these models will be called with `λ::Real` and not as `λ::Quantity`. Therefore the utility function mentioned below is redundant.
https://github.com/JuliaAstro/DustExtinction.jl/blob/1766089ca9b10a7892684509df3aff0e7b85ceee/src/color_laws.jl#L5

**Comment by mileslucas** [comment]
I’m fine with this. We can always add it back later if we need it. I’ll let @giordano make the call.

**Comment by giordano** [comment]
Note that `Quantity <: Number`, so
```julia
julia> Quantity <: Real
false
```
If we want to keep a single method we need to expand the signature to `λ::Number`

**Comment by mileslucas** [comment]
Yes, that's why I initially wrote this method, but we don't export it and the internal usage is always after a `ustrip`, so it's never actually used.
