### ISSUE TITLE
Tagging a new release

### ISSUE THREAD

**Issue by sefffal** [JuliaAstro/DustExtinction.jl#39]
There are commits to this repo that allow FITSIO to be 0.16 and Dirckx to be 0.5, but a release has not been tagged and registered from some time.

If we're okay to proceed, I'm happy to bump the version and trigger tag bot.

**Comment by mileslucas** [comment]
I've got it!

**Comment by mileslucas** [comment]
https://github.com/JuliaRegistries/General/pull/65752

**Comment by sefffal** [comment]
Thanks!

**Comment by sefffal** [comment]
The new version did not get auto-merged

**Comment by giordano** [comment]
https://github.com/JuliaRegistries/General/pull/67173
